[global]
    name = "HowTellYou"
[server]
    port = 8888
    config_path = "./config_iris.toml"
[database]
    ip = "192.168.21.131"
    port = 3306
    user = "root"
    password = "qwerty123456"
    database_name = "hty"
[secure]
    key = "W*qw#yL5AChsiBiN" # must be 16, 24, 32 length
    allowed_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz`~!@#$%^&*()-_=+[]{}\\|?><.,/1234567890"
    salt_length = 64

#Please do not make any arbitrary changes to the following content
[advanced]